export const ADD_TO_CART = 'ADD_TOT_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
// export const CHANGE_AMOUNT = 'CHANGE_AMOUNT';
export const CHANGE_AMOUNT_INCREASE = 'CHANGE_AMOUNT_INCREASE';
export const CHANGE_AMOUNT_DECREASE = 'CHANGE_AMOUNT_DECREASE';
export const GET_TOTAL = 'GET_TOTAL';
export const SAVE_CART_TO_LOCAL = 'SAVE_CART_TO_LOCAL';